### ISSUE TITLE
The maximal number of iterations maxit

### ISSUE THREAD

**Issue by noxmyn** [andersle/gpxplotter#20]
I am using gpx generated from the data of the owntracks program(android), which sends data via mqtt to my server.

The resulting gpx is normally torn off in any programs.
gpx has a minimal structure: coordinates and time.

If you take a piece of the track, it generates normally.
If I take a full track, I get an error:
`lib/python3.6/site-packages/scipy/interpolate/fitpack2.py:253: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)`

Data is transmitted every second for a total of 4700 points. ~ 79 minutes. With so many points, an error appears.
If I delete some points - 4660, then the graph is drawn.

**Comment by andersle** [comment]
The warning you get is probably from the part of the code that tries to estimate the velocity by fitting a spline (which uses the scipy method [UnivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html) from fitpack2.py). Note: These velocities are very noise and I am not using them myself (planning to add support to read them directly from a .tcx file instead, since they are then recorded by the gpx-device with better accuracy).

Does it work if you ignore/remove the plotting of velocities (some of the examples attempt to plot this)?

If you attach one of the failing gpx-files here I can troubleshoot it further to see how it can be fixed.

**Comment by andersle** [comment]
(Note to self - this is (probably) related to #22 #21)

**Comment by andersle** [comment]
Closed by PR #23 #25
